### ISSUE TITLE
Explore Laravel Pint as a linter

### ISSUE THREAD

**Issue by dmohns** [EnAccess/micropowermanager#100]
Being a Laravel project maybe it would be great to also adhere to the "official" Laravel Code Style: https://laravel.com/docs/11.x/pint

**Comment by pechtelt1** [comment]
@dmohns i think this is a good idea. Do you have some code style requirements or do you just want to have the default Laravel Pint?

**Comment by munyanezaarmel** [comment]
@dmohns If this issue is still relevant, I would be happy to take it on.

**Comment by dmohns** [comment]
Sure, it's still somewhat relevant. Feel free to take a look 👍 

Bear in mind that we recently adopted PHP-CS-Fixer, see https://github.com/EnAccess/micropowermanager/pull/99 So we'd have to check how the two interact.

**Comment by dmohns** [comment]
We are not going to use **Laravel Pint** as we already have PHP-CS-Fixer. For more details, see response here: https://github.com/EnAccess/micropowermanager/pull/364#issuecomment-2500511460
