### ISSUE TITLE
[Bug]: Routing error in `Targets New`

### ISSUE THREAD

**Issue by dmohns** [EnAccess/micropowermanager#124]
When trying to add a new Target via the Add button. The following error message appears: 

```
Failed to load resource: the server responded with a status of 400 (Bad Request)
```

<img width="454" alt="image" src="https://github.com/EnAccess/micropowermanager/assets/14202480/44185422-c9cd-42e9-baef-176f3eaa871e">

**Comment by beesaferoot** [comment]
Looked at this earlier, the endpoint `/api/meters/parameters/connection-types` seems to be used to get the number of customers.

But that endpoint no longer exists on the backend; I would like some clarity on what it was used for. @dmohns

**Comment by dmohns** [comment]
Ohh, maybe this is related to the deprecation of `MeterParameters` ? See https://github.com/EnAccess/micropowermanager/issues/375

Basically, `connection-type` should be read from the `Meter` object directly, not via the intermediate `MeterParameters`. Can you check if the meters endpoint exposes `connection-type`?

**Comment by beesaferoot** [comment]
I found the issue. You are right; the endpoint (`/api/meters/parameters/connection-types`) was previously used with association with `MeterParameters`.   I have replaced the missing endpoint to use data directly from `Meters`

The page now renders properly.
