### ISSUE TITLE
Consistent spelling in SideBar and endpoints

### ISSUE THREAD

**Issue by dmohns** [EnAccess/micropowermanager#127]
In the SideBar and routes currently we use a mix of singular and plural. Let's decide on a convention and consistently use it.

**Comment by beesaferoot** [comment]
@dmohns Can you give a bit more details to this issue?

**Comment by dmohns** [comment]
Back when I created this issues there were some inconsistencies with how the Routes (in frontend) were called. For example `meter` vs `meters` etc.. I think mostly this no longer applies. I will be closing this issue for now, as there isn't any action item _right now_. However, if you notice some inconsistencies, feel free to race them!
