### ISSUE TITLE
SteamaMeter Plugin not synchronizing with ui.steama.co data

### ISSUE THREAD

**Issue by morgist** [EnAccess/micropowermanager#165]
There is an issue with the SteamaMeter Plugin as synchronization with ui.steama.co is not possible, it does not display data after authenticating credentials from ui.steama.co

**Comment by dmohns** [comment]
Hey @morgist 

thanks for raising this issue here.

Could you please give us a bit more information about the error you encounter and your environment?

- Do you encounter any errors in log files or browser?
- Which version of MPM are you running? (self-hosted or cloud)
- If self-hosted, what is your setup?

**Comment by morgist** [comment]
There is no error or log files in the browser.
I am using the current version of MPM, i have try both the self-hosted and cloud version of the MPM.
The authentication after the plugin is enable is successful both data is not synchronized. 

I can share the more information if needed.

**Comment by dmohns** [comment]
Hey @morgist 

I identified a couple of issues with the SteamaCo Plugin. I will create separate issues linking to this one.

Unfortunately, it's a little hard for me to really deeply debug the issue, as I don't have a SteamaCo account setup right now. Would you be willing to join our Open Source in Energy Access Discord server, to discuss this in more detail? https://community.oseas.org (`#micropowermanager` channel)

**Comment by morgist** [comment]
Great Work! I have join the Discord Server.

**Comment by dmohns** [comment]
Hello @morgist 

the related and identified issues have been resolved 🎉 I will be closing this issues. Please feel free to re-open if you encounter any further issues.
