### ISSUE TITLE
Rename `ErrorHander` to `ErrorHandler`

### ISSUE THREAD

**Issue by dmohns** [EnAccess/micropowermanager#196]
**Background:** In the frontend application we use a helper called `ErrorHander` which implements a simple error handler. The naming is a simple typo and should be fixed to `ErrorHandler`. See https://github.com/EnAccess/micropowermanager/blob/main/src/frontend/src/Helpers/ErrorHander.js

**Scope:** Please change the filename and adapt all imports accordingly.

**Acceptance criteria:** As we currently do not provide fully-automated tests, please provide an example of the new error handler working correctly. For example a screenshot of a local dev environment, where the error is shown with all information.

**Comment by CodingWithError** [comment]
Can you provide some information about this. And assign this me

**Comment by dmohns** [comment]
Hey @CodingWithError I updated this ticket's description with all required information. Please confirm that you want to be assigned to it. And thanks in advance for your contribution 🙏

**Comment by CodingWithError** [comment]
Hey @dmohns raised a PR please check
