### ISSUE TITLE
Registration Process Fails with Existing Credentials or Similar Email Addresses Without Specific Error Message

### ISSUE THREAD

**Issue by Delyc** [EnAccess/micropowermanager#232]
Specifically, the process fails under the following conditions:

1. **Existing User Credentials:** When trying to register with credentials that are already associated with an existing user account.

2. **Similar Email Addresses:** When the email entered in the second email field is similar to the one provided in the first email field.

In both scenarios, the application does not provide a specific error message indicating the cause of the failure. Instead, it only displays a generic message stating "something went wrong.

**Comment by beesaferoot** [comment]
I will take on this for a start @dmohns

**Comment by beesaferoot** [comment]
Hi there, I managed to get the custom error message working in the case of an already existing account. However, I have not been able to reproduce the similar email address case; can you provide a list of steps to produce it if possible?

@Delyc @dmohns

**Comment by dmohns** [comment]
> Hi there, I managed to get the custom error message working in the case of an already existing account. However, I have not been able to reproduce the similar email address case; can you provide a list of steps to produce it if possible?
> 
> [@Delyc](https://github.com/Delyc) [@dmohns](https://github.com/dmohns)

I think the steps are to first create org A with user B. Then try to create a second org. If the user email for that second org is already existent in org A, then the error should be fired?

**Comment by devjhane** [comment]
> > Hi there, I managed to get the custom error message working in the case of an already existing account. However, I have not been able to reproduce the similar email address case; can you provide a list of steps to produce it if possible?
> > [@Delyc](https://github.com/Delyc) [@dmohns](https://github.com/dmohns)
> 
> I think the steps are to first create org A with user B. Then try to create a second org. If the user email for that second org is already existent in org A, then the error should be fired?

I believe what you described is for "Existing User Credentials" as noted on the issue description. 

The second condition (no 2) for "Similar Email Addresses" is where I may need more clarity on. 


Using the same email for both company and personal email seems to work just fine without any error from the backend.

**Comment by beesaferoot** [comment]
> > Hi there, I managed to get the custom error message working in the case of an already existing account. However, I have not been able to reproduce the similar email address case; can you provide a list of steps to produce it if possible?
> > [@Delyc](https://github.com/Delyc) [@dmohns](https://github.com/dmohns)
> 
> I think the steps are to first create org A with user B. Then try to create a second org. If the user email for that second org is already existent in org A, then the error should be fired?

I believe what you described is for "Existing User Credentials" as noted on the issue description. 

The second condition (no 2) for "Similar Email Addresses" is where I may need more clarity on. 


Using the same email for both company and personal email seems to work just fine without any error from the backend.

**Comment by dmohns** [comment]
> > > Hi there, I managed to get the custom error message working in the case of an already existing account. However, I have not been able to reproduce the similar email address case; can you provide a list of steps to produce it if possible?
> > > [@Delyc](https://github.com/Delyc) [@dmohns](https://github.com/dmohns)
> > 
> > 
> > I think the steps are to first create org A with user B. Then try to create a second org. If the user email for that second org is already existent in org A, then the error should be fired?
> 
> I believe what you described is for "Existing User Credentials" as noted on the issue description.
> 
> The second condition (no 2) for "Similar Email Addresses" is where I may need more clarity on.
> 
> Using the same email for both company and personal email seems to work just fine without any error from the backend.

Ohh, sorry misunderstood 👌 

My understanding of the second error was, that it appears when we are trying to use the same email for company contact and for user account. @Delyc could you provide more input here?

**Comment by dmohns** [comment]
Maybe there is a difference between company contact email and personal email being already used? I can confirm that there is no problem having concat and personal email being the same. 

Let's change the error messages in a way that it becomes clear whether the company contact or personal email is already used. And remove the error message regarding company contact and personal email having to be different.

**Comment by beesaferoot** [comment]
Will check if there is such a difference from the backend response and update the error message accordingly.

**Comment by beesaferoot** [comment]
I can confirm there are differences when a company email already exists and when an "admin" user email does exists.


These has been handled as well as the text.


![Image](https://github.com/user-attachments/assets/49261277-68e2-4524-a370-9bd0b787bdd5)
