### ISSUE TITLE
[Bug]: "CORS Error While Creating Account Locally - Is CORS Configured on Backend?

### ISSUE THREAD

**Issue by munyanezaarmel** [EnAccess/micropowermanager#308]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/EnAccess/micropowermanager/blob/main/CONTRIBUTING.md) for this project, if it exists.
- [x] I agree to follow the [Code of Conduct](https://github.com/EnAccess/micropowermanager/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/EnAccess/micropowermanager/issues) for a feature request that matches the one I want to file, without success.

### Expected Behavior

When creating an account locally, I expect the request to be processed without triggering a CORS error. The frontend should successfully communicate with the backend, allowing account creation to proceed smoothly, with the appropriate response being returned from the server

### Actual Behavior

I am encountering a CORS error when trying to create an account locally. I wanted to confirm whether CORS has been properly set up on the backend ![Image](https://github.com/user-attachments/assets/e9676761-f016-4d5e-863b-fac73376d6e9)

### Steps to reproduce

If the issue is that CORS is not configured in the backend, it's not my problem. Please assign this issue to me so I can fix it

### What operating system(s) are you using?

Ubuntu

**Comment by munyanezaarmel** [comment]
@dmohns

**Comment by dmohns** [comment]
This should be fixed in the latest release: https://github.com/EnAccess/micropowermanager/releases/tag/v0.0.2

@munyanezaarmel can you check and close this issue, if fixed?
